### ISSUE TITLE
Masking with hints

### ISSUE THREAD

**Issue by piotrmwojcik** [gkakogeorgiou/attmask#1]
While the paper says that AttnMask-Hint strategy reveals a certain portion of tokens masked by AttnMask-High ('we remove from the initial set MH a small number'), the implementation actually masks only a fixed portion of tokens (show_max) and reveal a fraction of them. This means that due to the small value of show_max, very often no masking is used. Could you please comment on that?
```
       # Get a mask of the top show(%) most attended tokens
        top_masks = get_mask(attention,
                             1,
                             masking_mode,
                             show_max
                             )
```

**Comment by gkakogeorgiou** [comment]
Hi @piotrmwojcik,

I don't observe any issues. When AttMask-Hint is selected, initially, the same computation as AttMask-High takes place (https://github.com/gkakogeorgiou/attmask/blob/master/attmask.py#L9-L13), resulting in "masks." Then, the code you mentioned runs to find the most highly attended tokens (https://github.com/gkakogeorgiou/attmask/blob/master/attmask.py#L19-L23), resulting in "top_masks." Finally, this part (https://github.com/gkakogeorgiou/attmask/blob/master/attmask.py#L25-L26) reveals some tokens of AttMask-High "masks" based on "top_masks", resulting in the final "masks."

Let me know if something still needs to be clarified.

I appreciate your interest,
Ioannis

**Comment by piotrmwojcik** [comment]
Hi @gkakogeorgiou, thank you very much for the explanation, it is clear now!
